/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/Booking/availableseat/direct/{flightId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    source?: string;
                    direction?: string;
                };
                header?: never;
                path: {
                    flightId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AvailableSeatDto"][];
                        "application/json": components["schemas"]["AvailableSeatDto"][];
                        "text/json": components["schemas"]["AvailableSeatDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Booking/availableseat/connecting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    flight1Id?: number;
                    flight2Id?: number;
                    source1?: string;
                    source2?: string;
                    direct?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AvailableSeatDto"][];
                        "application/json": components["schemas"]["AvailableSeatDto"][];
                        "text/json": components["schemas"]["AvailableSeatDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Booking/selectseat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BookeSeatRequestDto"];
                    "text/json": components["schemas"]["BookeSeatRequestDto"];
                    "application/*+json": components["schemas"]["BookeSeatRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Booking/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BookingInfoDto"];
                    "text/json": components["schemas"]["BookingInfoDto"];
                    "application/*+json": components["schemas"]["BookingInfoDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Booking/confirm_after-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConfirmBookingRequestDto"];
                    "text/json": components["schemas"]["ConfirmBookingRequestDto"];
                    "application/*+json": components["schemas"]["ConfirmBookingRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/CombinedFlights/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    departAirport?: string;
                    arriveAirport?: string;
                    departureDate?: string;
                    returnDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FlightSearchResponses"];
                        "application/json": components["schemas"]["FlightSearchResponses"];
                        "text/json": components["schemas"]["FlightSearchResponses"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/PaymentContoller/create-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": string;
                    "text/json": string;
                    "application/*+json": string;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AvailableSeatDto: {
            seatNumber?: string | null;
        };
        BookeSeatRequestDto: {
            flightType?: components["schemas"]["FlightTypes"];
            /** Format: int32 */
            flightId?: number | null;
            /** Format: int32 */
            flight1Id?: number | null;
            /** Format: int32 */
            flight2Id?: number | null;
            flightSource?: string | null;
            flight1Sournce?: string | null;
            flight2Source?: string | null;
            seatNumber?: string | null;
            /** Format: uuid */
            sessionId?: string;
            direction?: string | null;
        };
        BookingInfoDto: {
            /** Format: uuid */
            sessionId?: string;
            firstName?: string | null;
            lastName?: string | null;
            email?: string | null;
            phoneNumber?: string | null;
            /** Format: date-time */
            dateOfBirth?: string;
            gender?: string | null;
            /** Format: double */
            price?: number;
            flights?: components["schemas"]["FlightLegDto"][] | null;
        };
        CombinedFlightDto: {
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            departDateTime?: string;
            /** Format: date-time */
            arriveDateTime?: string;
            departAirport?: string | null;
            arriveAirport?: string | null;
            flightNumber?: string | null;
            flight_source?: string | null;
            /** Format: double */
            price?: number;
            currency?: string | null;
            /** Format: date-span */
            duration?: string;
        };
        ConfirmBookingRequestDto: {
            /** Format: uuid */
            sessionId?: string;
        };
        ConnectingFlightDto: {
            /** Format: int32 */
            flight1_Id?: number;
            /** Format: int32 */
            flight2_Id?: number;
            flight1_DepartAirport?: string | null;
            connectingAirport?: string | null;
            flight2_ArriveAirport?: string | null;
            /** Format: date-time */
            flight1_DepartureDateTime?: string;
            /** Format: date-span */
            flight1Duration?: string;
            /** Format: double */
            price?: number;
            /** Format: date-span */
            flight2Duration?: string;
            /** Format: date-time */
            flight1_ArrivalDateTime?: string;
            /** Format: date-time */
            flight2_DepartureDateTime?: string;
            /** Format: date-time */
            flight2_ArrivalDateTime?: string;
            /** Format: date-span */
            allFlightDuration?: string;
            /** Format: date-span */
            transitTime?: string;
            indirectFlightNumber?: string | null;
            flight1_Source?: string | null;
            flight2_Source?: string | null;
            currency?: string | null;
        };
        FlightLegDto: {
            /** Format: int32 */
            flightId?: number;
            flightSource?: string | null;
            direction?: string | null;
        };
        FlightSearchResponses: {
            directDepartFlights?: components["schemas"]["CombinedFlightDto"][] | null;
            connectingDepartFlights?: components["schemas"]["ConnectingFlightDto"][] | null;
            directReturnFlights?: components["schemas"]["CombinedFlightDto"][] | null;
            connectingReturnFlights?: components["schemas"]["ConnectingFlightDto"][] | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        FlightTypes: 1 | 2;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
